databases:
  - name: cannabistracker-db
    databaseName: cannabistracker
    user: cannabistracker

services:
  - type: web
    name: cannabistracker-web
    env: node
    plan: free
    buildCommand: npm install ; npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cannabistracker-db
          property: connectionString
